README.md, runner/README.md
Hi Nima.
I just looked at the readme files again and found these spelling errors.
Also, I have a suggestion after trying to run Annotator:
- run.py requires the xmltodict module, which needs to be installed manually. Maybe this should be mentioned somewhere in the Installation section, or in the Running the Script section. Install the module with "pip install xmltodict"
=> Spelling on the README.md files AND some suggestions

scanner/src/main/java/edu/ucr/cs/riple/scanner/Config.java, scanner/src/main/java/edu/ucr/cs/riple/scanner/DummyOptionsConfig.java, scanner/src/main/java/edu/ucr/cs/riple/scanner/ErrorProneCLIFlagsConfig.java, scanner/src/main/java/edu/ucr/cs/riple/scanner/Serializer.java, scanner/src/main/java/edu/ucr/cs/riple/scanner/XMLUtil.java, scanner/src/test/java/edu/ucr/cs/riple/scanner/ClassInfoTest.java, scanner/src/test/java/edu/ucr/cs/riple/scanner/ConfigurationTest.java, scanner/src/test/java/edu/ucr/cs/riple/scanner/tools/SerializationTestHelper.java, scanner/src/test/resources/edu/ucr/cs/riple/scanner/SampleClassForTest.java
This PR is a follow up to GH-18 and resolves #17. With this PR, an exception will be thrown at the time a wrong configuration for the `Scanner` checker (`null` value for `Output` or `ConfigPath`) and will prevent propagation of `null` value through the program.
=> Adds a guard for wrong configurations.

scanner/src/main/java/edu/ucr/cs/riple/scanner/out/MethodInfo.java, scanner/src/main/java/edu/ucr/cs/riple/scanner/out/TrackerNode.java, scanner/src/test/java/edu/ucr/cs/riple/scanner/MethodInfoTest.java, scanner/src/test/java/edu/ucr/cs/riple/scanner/tools/MethodInfoDisplay.java
This PR adds visibility and return type of method to list of informations serialized on output.
```
id, class, method, parent, size, flags, nullable, parameters, uri
```
will be changed to:
```
id, class, method, parent, size, flags, nullable, visibility, non-primitive-return, parameters, uri
```
If the method is returning a `primitive` type of `void` the `non-primitive-return` value will be set to `false` and `true` otherwise.
=> Serialize method visibility / return type

core/src/main/java/edu/ucr/cs/riple/core/metadata/field/FieldDeclarationAnalysis.java, injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java, injector/src/main/java/edu/ucr/cs/riple/injector/SignatureMatcher.java, injector/src/main/java/edu/ucr/cs/riple/injector/exceptions/TargetClassNotFound.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/Location.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/OnMethod.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/OnParameter.java, injector/src/test/java/edu/ucr/cs/riple/injector/ClassSearchTest.java
This PR fixes #27 by adding a new type of exception `TargetClassNotFound`. With this PR annotator will not crash if the class is not found, and will instead log this information for later debugging. 
Also added a test to verify, annotator will not fail and the desired error message is correctly reported in the `err` console.
=> Prevent crash when a target class is not located with better logging mechanism.

core/src/test/java/edu/ucr/cs/riple/core/BaseCoreTest.java, core/src/test/java/edu/ucr/cs/riple/core/tools/CoreTestHelper.java, core/src/test/java/edu/ucr/cs/riple/core/tools/Utility.java, core/src/test/resources/templates/downstream-dependency-test/DepA/build.gradle, core/src/test/resources/templates/downstream-dependency-test/DepB/build.gradle, core/src/test/resources/templates/downstream-dependency-test/DepC/build.gradle, core/src/test/resources/templates/downstream-dependency-test/Target/build.gradle, core/src/test/resources/templates/unittest/build.gradle
This PR address #31 by adding `gradle` command line arguments to update config files based on the values computed at runtime (e.g. path to test root directory).
This PR removes all the codes for rewriting config files.
All `build.gradle` files in test project templates, include `project.getProperty("nullaway-config-path")` and `project.getProperty("scanner-config-path")` which will be passed in build command via gradle command line arguments: `-Pscanner-config-path` and `-Pnullaway-config-path`.
=> Add Gradle command line arguments

core/src/main/java/edu/ucr/cs/riple/core/util/Utility.java, core/src/test/java/edu/ucr/cs/riple/core/ConfigurationTest.java
This PR resolves #38 by adding a `UUID` to every generated config file to guarantee with same configuration values, content of the file is still modified. This will trigger build systems to rebuild the module whenever annotator requests rebuilds.
Please note: `UUID` alone might not be effective unless the build systems takes the config files states into account in their caching strategies.
=> Fix #38, Add UUID to every config file

core/src/main/java/edu/ucr/cs/riple/core/Annotator.java, library-model-loader/src/main/resources/edu/ucr/cs/riple/librarymodel/nullable-methods.tsv
This PR removes the main part of the downstream dependency analysis from the iteration loop since the state of the downstream dependency module is not changing along the iterations. All computations are valid along the iteration can be reused.
**Note**: This assumption is valid as long as we are analyzing the whole set of public methods on downstream dependencies, by the time this changes (e.g. only analyzing methods that `NullAway` is suggesting to be `@Nullable`) we have to perform the analysis in each iteration.
=> Remove downstream dependency analysis from loop

core/build.gradle, core/src/test/resources/templates/downstream-dependency-test/DepA/build.gradle, core/src/test/resources/templates/downstream-dependency-test/DepB/build.gradle, core/src/test/resources/templates/downstream-dependency-test/DepC/build.gradle, core/src/test/resources/templates/downstream-dependency-test/Target/build.gradle, core/src/test/resources/templates/unittest/build.gradle
This PR resolves #50 by removing all hardcoded values (`NullAway` \ `TypeAnnotatorScanner` version values) and uses environment variables to set up test project templates configurations with the current development version.
=> Fix #50 by removing hard coded values and using environment variables

.github/workflows/continuous-integration.yml, README.md
This PR resolves #57 by showing the status of the `CI` jobs in the landing `readme.md`.
=> Update readme to show status of CI jobs

core/src/main/java/edu/ucr/cs/riple/core/metadata/method/MethodDeclarationTree.java, core/src/test/java/edu/ucr/cs/riple/core/CoreTest.java, type-annotator-scanner/src/main/java/edu/ucr/cs/riple/scanner/out/MethodInfo.java
This PR resolves #75 by updating `TOP` node id and index. Also making sure that `getClosestSuperMethod()` only returns methodNode for discovered nodes. (Declared in module)
=> Fix #75 by updating TOP method node id and returned overridden methods

gradle/dependencies.gradle
This PR resolves #78 by downgrading javaparser to version `3.24.0`.
---
#78 should be open until we find a reproducible example and report back to `javaparser`.
=> Fix #78 by downgrading javaparser version to 3.24.0

core/src/main/java/edu/ucr/cs/riple/core/log/Log.java
This PR adds javadoc and the copyright header to [Log](https://github.com/nimakarimipour/NullAwayAnnotator/tree/master/core/src/main/java/edu/ucr/cs/riple/core/log) package. This is part of the  ultimate goal of adding javadoc to all packages in `Core` module.
=> Add javadoc to log class.

injector/src/main/java/edu/ucr/cs/riple/injector/changes/AddAnnotation.java, injector/src/main/java/edu/ucr/cs/riple/injector/changes/RemoveAnnotation.java
This PR adds refines `equals()` definition for `Change` subclasses.
=> Add missing equals to changes

injector/src/main/java/edu/ucr/cs/riple/injector/changes/AddAnnotation.java, injector/src/main/java/edu/ucr/cs/riple/injector/changes/RemoveAnnotation.java
This PR is a follow up PR for #83 where `equals()` implementation were added to subclasses of `Change` class but `hashcode` implementation was missed. This PR adds the hashcode implementation.
=> Add hashcode to Change subclasses

core/src/main/java/edu/ucr/cs/riple/core/injectors/PhysicalInjector.java, injector/src/main/java/edu/ucr/cs/riple/injector/Injector.java
This PR simply renames methods used in calling injector APIs. It was not introducing any bugs even though with wrong API names the correct code was still executing.
This is merely a rename of methods. I am going to land this one for now, please let me know if there is anything you would like to change here and I will bring this back.
=> Rename methods in injector

type-annotator-scanner/src/main/java/edu/ucr/cs/riple/scanner/TypeAnnotatorScanner.java, type-annotator-scanner/src/main/java/edu/ucr/cs/riple/scanner/out/MethodInfo.java
This PR resolves #93 by passing the relevant `VisitorState` for fetching the `URI`.
This will enable to Annotator to correctly add `@NullUnmarked` annotations as generating annotation requests requires getting URIs from `MethodDeclarationTree`.
=> Fix URIs in MethodDeclarationTree nodes

core/build.gradle, core/src/main/java/edu/ucr/cs/riple/core/Annotator.java, core/src/main/java/edu/ucr/cs/riple/core/Config.java, core/src/main/java/edu/ucr/cs/riple/core/log/Log.java, core/src/test/java/edu/ucr/cs/riple/core/CoreTest.java, core/src/test/java/edu/ucr/cs/riple/core/tools/CoreTestHelper.java
This PR resolves #86 by adding the specific analysis mode which deactivates inference of Annotator and all errors are resolved with `@NullUnmarked` annotations.
To enable this feature flag below must be passed:
```shell
-di, --deactivate-inference
```
Or 
```json
"INFERENCE_ACTIVATION": false
```
Please note: When inference is deactivated, force resolve mode is automatically activated to resolve all remaining errors with `@NullUnmarked` injection.
-----
=> Add inference deactivation mode.

build.gradle, core/build.gradle, gradle.properties, injector/build.gradle, qual/build.gradle, type-annotator-scanner/build.gradle
This PR adds release configurations for `core` and `type-annotator-scanner` modules.
Note: `core` will be renamed to `annotator-core` as a followup.
=> Release scripts

core/src/main/java/edu/ucr/cs/riple/core/Annotator.java, core/src/test/java/edu/ucr/cs/riple/core/CoreTest.java
This PR resolves #73 by adding `@NullUnmarked` annotations for called methods in field initializations that received a `@Nullable`.
=> Fix #73 by extending list of NullUnmarked injections.

injector/build.gradle, injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java, injector/src/main/java/edu/ucr/cs/riple/injector/Printer.java, injector/src/test/java/edu/ucr/cs/riple/injector/LexicalPreservationTest.java, injector/src/test/java/edu/ucr/cs/riple/injector/OnParameterInjectionTest.java, injector/src/test/java/edu/ucr/cs/riple/injector/tools/InjectorTestHelper.java, injector/src/test/resources/benchmark_expected_10.java, injector/src/test/resources/benchmark_expected_11.java, injector/src/test/resources/benchmark_expected_12.java, injector/src/test/resources/benchmark_expected_13.java, injector/src/test/resources/benchmark_expected_14.java, injector/src/test/resources/benchmark_expected_15.java, injector/src/test/resources/benchmark_expected_16.java, injector/src/test/resources/benchmark_expected_18.java, injector/src/test/resources/benchmark_expected_19.java, injector/src/test/resources/benchmark_expected_20.java, injector/src/test/resources/benchmark_expected_21.java, injector/src/test/resources/benchmark_expected_3.java, injector/src/test/resources/benchmark_expected_4.java, injector/src/test/resources/benchmark_expected_5.java, injector/src/test/resources/benchmark_expected_6.java, injector/src/test/resources/benchmark_expected_7.java, injector/src/test/resources/benchmark_expected_8.java, injector/src/test/resources/benchmark_expected_9.java, injector/src/test/resources/simple_expected_1.java, injector/src/test/resources/simple_expected_2.java, injector/src/test/resources/simple_expected_3.java
Due to a bug in injector test infra, tests in `ClassSearchTest` were excluded from CI. This PR adds these tests back.
The expected output of these tests had to be updated as before #90 tests outputs were compared to their expected output regardless of existing white spaces. But after #90 and #102, we used a stricter way to compare the expected output (tools output must match the expected output byte to byte), therefore the expected output of these tests had been updated as well.
@msridhar @lazaroclapp This is a straightforward change and it mostly contains updating expected output results of tests (updating white spaces), therefore I am going to land this now, please let me know if there is anything you would like to discuss and I will bring this back.
=> Bug fix for Injector test infrastructure

annotator-core/src/main/java/edu/ucr/cs/riple/core/util/Utility.java, annotator-scanner/src/main/java/edu/ucr/cs/riple/scanner/Config.java, annotator-scanner/src/main/java/edu/ucr/cs/riple/scanner/ScannerConfigWriter.java, annotator-scanner/src/test/java/edu/ucr/cs/riple/scanner/AnnotatorScannerBaseTest.java
This PR simply extracts the config writer inside the `annotator-scanner` module into a separate standalone class, and reuses it in `annotator-core` module.
Please note that this is a preparation for the upcoming PR handling region selection for generated code.
=> Extract AnnotatorScanner config writer into a separate class.

annotator-core/src/main/java/edu/ucr/cs/riple/core/adapters/NullAwayV0Adapter.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/adapters/NullAwayV1Adapter.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/trackers/FieldRegionTracker.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/trackers/MethodRegionTracker.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/trackers/TrackerNode.java
This PR updates tracker nodes to receive a region as a parameter instead of raw region class name and region member. 
Please note that this is a preparation for the upcoming PR handling region selection for generated code.
=> Update tracker node construction

injector/src/main/java/edu/ucr/cs/riple/injector/changes/AddMarkerAnnotation.java, injector/src/main/java/edu/ucr/cs/riple/injector/changes/AddSingleElementAnnotation.java, injector/src/main/java/edu/ucr/cs/riple/injector/changes/Change.java, injector/src/main/java/edu/ucr/cs/riple/injector/changes/RemoveAnnotation.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/Location.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/OnField.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/OnMethod.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/OnParameter.java, injector/src/test/java/edu/ucr/cs/riple/injector/BasicTest.java
This PR removes `duplicate` method on `Location` instances which is unused in the source code and only used in one unit tests. 
This PR is straightforward and simply removes an used method, I am going to land this PR once CI passes, if there is anything you would like to discuss, please let me know and I will bring this back.
Please note, that this was required for #121 which resolves flaky CI issue.
=> Remove unused "duplicate" API on Location instances

annotator-core/src/main/java/edu/ucr/cs/riple/core/AnalysisMode.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/Annotator.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/Report.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/BasicEvaluator.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/graphprocessor/AbstractConflictGraphProcessor.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/suppliers/DownstreamDependencySupplier.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/suppliers/Supplier.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/suppliers/TargetModuleSupplier.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/global/DownstreamImpactCache.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/global/DownstreamImpactCacheImpl.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/global/DownstreamImpactEvaluator.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/global/VoidDownstreamImpactCache.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/graph/Node.java
This PR simply includes renaming in #111 (through received comments in reviews). The purpose of this PR is to make #111 more understandable as this change is unrelated to #111. I am going to land this since it is a very straightforward name change. Please let me know if you would like to discuss more regarding this change and I will bring this back. Thank you. @msridhar @lazaroclapp. 
Renames are:
1. `triggeredFixesOnDownstream` to `triggeredFixesFromDownstream`.
2. `globalAnalyzer` to `downstreamImpactCache`.
=> Rename to triggeredFixesOnDownstream to triggeredFixesFromDownstream

annotator-scanner/src/main/java/edu/ucr/cs/riple/scanner/AnnotatorScanner.java, annotator-scanner/src/main/java/edu/ucr/cs/riple/scanner/Serializer.java, annotator-scanner/src/main/java/edu/ucr/cs/riple/scanner/out/ImpactedRegion.java
I found #132 a bit hard to understand because I couldn't understand what exactly `TrackerNode` was for.  Here I renamed it to `ImpactedRegion` and added some documentation, which I think is helpful.  There should be no functional change here.
=> Rename TrackerNode to ImpactedRegion and document

annotator-core/src/main/java/edu/ucr/cs/riple/core/Annotator.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/index/Error.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/trackers/Region.java, annotator-core/src/test/java/edu/ucr/cs/riple/core/CoreTest.java
This PR fixes a bug which was causing annotator to only inject `@NullUnmarked` annotations on methods. This PR fixes this issue and enables Annotator to add `@NullUnmarked` annotation for errors enclosed by constructors.
=> Add @NullUnmarked on constructors

injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java, injector/src/test/java/edu/ucr/cs/riple/injector/ClassSearchTest.java, injector/src/test/resources/enum_search.java, injector/src/test/resources/enum_search_expected_1.java, injector/src/test/resources/enum_search_expected_2.java, injector/src/test/resources/enum_search_expected_3.java
This PR resolves #124 by updating class search algorithm with prioritizing enum constants while doing a tree traversal. This will help injector to assign correct flat names to classes in a tree by visiting enum constants before other existing anonymous classes.
=> Resolves #124 by updating class search for enum constants

annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/trackers/MethodRegionTracker.java, annotator-core/src/test/java/edu/ucr/cs/riple/core/CoreTest.java, annotator-scanner/src/main/java/edu/ucr/cs/riple/scanner/AnnotatorScanner.java, annotator-scanner/src/main/java/edu/ucr/cs/riple/scanner/Serializer.java, annotator-scanner/src/main/java/edu/ucr/cs/riple/scanner/SymbolUtil.java, annotator-scanner/src/test/java/edu/ucr/cs/riple/scanner/MethodCallTrackerTest.java, annotator-scanner/src/test/java/edu/ucr/cs/riple/scanner/MethodImpactedRegionTest.java
This pull request extends the set of impacted regions for changes made to methods. Prior to this pull request, only call sites (and overriding methods) were taken into consideration as impacted regions for changes to methods. However, the use of lambda expressions or method references can actually extend the set of impacted regions and these should also be included. See example below:
```java
public class Main {
public void f(Foo r){ }
public void baz1(){
f(new Foo(){
public void bar(Object o){
t(o);
}
});
}
public void baz2(){
f(e -> t(e));
}
public void baz3(){
f(this::t);
}
public void t(Object o){ }
}
interface Foo{
void bar(Object o);
}
```
For example, if the `o` parameter of the `bar` method in `Foo` is annotated as `@Nullable`, the regions `baz2` and `baz3` were previously not …
=> Extend impacted regions by a method change

annotator-core/src/main/java/edu/ucr/cs/riple/core/Annotator.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/field/FieldInitializationStore.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/Location.java
This PR renames `FieldInitializationAnalysis` to `FieldInitializationStore` along minor refactoring for return value of `findInitializers()` to Set rather a Stream. It also prepares the codebase for the upcoming PR.
=> Rename FieldInitializationAnalysis to FieldInitializationStore

annotator-core/src/main/java/edu/ucr/cs/riple/core/Annotator.java
This PR simply moves the declaration of `FieldInitializationStore` to body of `preprocess` as a local variable declaration rather than a field declaration. This field is only used once inside a method.
=> Convert FieldInitializationStore to a local declaration in preprocess method.

annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/trackers/CompoundTracker.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/trackers/FieldRegionTracker.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/trackers/MethodRegionTracker.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/trackers/ParameterRegionTracker.java
This PR simply renames some field or local variables to `methodDeclarationTree` rather than the ambiguous name `tree`.
=> Rename tree to methodDeclarationTree in fields to resolve ambiguity.

annotator-scanner/src/main/java/edu/ucr/cs/riple/scanner/AnnotatorScanner.java, annotator-scanner/src/test/java/edu/ucr/cs/riple/scanner/ConfigurationTest.java
This PR adds the missing flag control for serialization for constructor invocation. It also adds a configuration to test to verify no output is created once all flags are turned off.
=> Add missing flag control for constructor invocation serialization

annotator-core/build.gradle, annotator-core/src/main/java/edu/ucr/cs/riple/core/Config.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/adapters/NullAwayV3Adapter.java, annotator-scanner/src/main/java/edu/ucr/cs/riple/scanner/AnnotatorScanner.java, annotator-scanner/src/main/java/edu/ucr/cs/riple/scanner/Serializer.java, annotator-scanner/src/main/java/edu/ucr/cs/riple/scanner/out/ImpactedRegion.java, annotator-scanner/src/main/java/edu/ucr/cs/riple/scanner/out/MethodInfo.java, injector/src/main/java/edu/ucr/cs/riple/injector/SignatureMatcher.java, injector/src/test/java/edu/ucr/cs/riple/injector/BasicTest.java, injector/src/test/java/edu/ucr/cs/riple/injector/ComprehensiveTest.java, injector/src/test/java/edu/ucr/cs/riple/injector/OnMethodInjectionTest.java, injector/src/test/java/edu/ucr/cs/riple/injector/OnMethodSearchTest.java, injector/src/test/java/edu/ucr/cs/riple/injector/OnParameterInjectionTest.java, injector/src/test/java/edu/ucr/cs/riple/injector/RemovalTest.java
~~This PR requires release of NullAway `0.10.10`.~~ NullAway `0.10.10` is released.
This PR updates NullAway test version to `0.10.10`. The main update in this version is on the serialization change. 
In the newest version, method signatures does not contain any annotation or type arguments, this PR adapts injector to work with this serialization to locate the method and also update scanner to use the same logic for serializing method signatures.
Please note that previously Injector was written to parse complicated cases such as case below:
```
foo(@edu.ucr.Custom({"arg1, "arg2}) java.util.Map<A.B.C, A.B.D>)
```
Wheres in the latest version of serialization for the method above, we receive input below:
```
foo(java.util.Map)
```
Therefore, the parsing logic, along the input for some unit …
=> Update NullAway test version to 0.10.10

annotator-core/src/test/java/edu/ucr/cs/riple/core/AnalysisModeTest.java, annotator-core/src/test/java/edu/ucr/cs/riple/core/BaseCoreTest.java, annotator-core/src/test/java/edu/ucr/cs/riple/core/CoreTest.java, annotator-core/src/test/java/edu/ucr/cs/riple/core/DownstreamAnalysisTest.java, annotator-core/src/test/java/edu/ucr/cs/riple/core/InheritanceTest.java, annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/CoreTestHelper.java, annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/TReport.java, annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/Utility.java
This PR adds the missing javadoc to test package in `annotator-core` module.
=> Add javadoc to test package for annotator-core

injector/src/main/java/edu/ucr/cs/riple/injector/Printer.java, injector/src/main/java/edu/ucr/cs/riple/injector/modifications/Deletion.java, injector/src/main/java/edu/ucr/cs/riple/injector/modifications/Insertion.java, injector/src/main/java/edu/ucr/cs/riple/injector/modifications/Modification.java, injector/src/main/java/edu/ucr/cs/riple/injector/modifications/Replacement.java, injector/src/main/java/edu/ucr/cs/riple/injector/modifications/SinglePositionModification.java
This PR updates the `Modification` abstract class to an interface. It prepares the architecture for upcoming PR which enables adding annotations in local variables along its type arguments.
=> Convert Modification abstract class to an interface

injector/src/main/java/edu/ucr/cs/riple/injector/changes/Change.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/Location.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/OnClass.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/OnField.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/OnMethod.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/OnParameter.java
This PR updates the javadoc comment for `visit` method in `Location` class. And also adds the required `@Nullable` annotations to `apply` methods and its overriding methods.
=> Javadoc update and add @Nullable annotations in Injector module

injector/src/main/java/edu/ucr/cs/riple/injector/changes/AddMarkerAnnotation.java, injector/src/main/java/edu/ucr/cs/riple/injector/changes/AddSingleElementAnnotation.java, injector/src/main/java/edu/ucr/cs/riple/injector/changes/Change.java, injector/src/main/java/edu/ucr/cs/riple/injector/changes/RemoveAnnotation.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/Location.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/OnClass.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/OnField.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/OnMethod.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/OnParameter.java
This PR updates the method below:
```java
Modification visit(NodeWithAnnotations<?> node, Range range)
```
To
```java
<T extends NodeWithAnnotations<?> & NodeWithRange<?>> Modification visit(T node)
```
Since the value for `range` is retrievable from the class implementing `NodeWithAnnotations `, all calls to this method were as below:
```
visit(node, node.getRange)
```
With this update, all calls are changed to simply:
```
visit(node)
```
=> Refactor Change#visit method in injector module

injector/src/main/java/edu/ucr/cs/riple/injector/Injector.java
This PR removes the redundant `Lexical Preserving Printer` setup after parsing each compilation unit tree.
=> Remove lexical preserving printer setup

annotator-core/src/main/java/edu/ucr/cs/riple/core/Annotator.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/BaseCache.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/TargetModuleCache.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/downstream/DownstreamImpact.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/downstream/DownstreamImpactCacheImpl.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/downstream/DownstreamImpactEvaluator.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/graphprocessor/AbstractConflictGraphProcessor.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/graphprocessor/ParallelConflictGraphProcessor.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/graphprocessor/SequentialConflictGraphProcessor.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/suppliers/AbstractSupplier.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/suppliers/DownstreamDependencySupplier.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/suppliers/Supplier.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/suppliers/TargetModuleSupplier.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/graph/Node.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/index/Error.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/method/MethodRecord.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/method/MethodRegistry.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/trackers/CompoundTracker.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/trackers/FieldRegionTracker.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/trackers/MethodRegionTracker.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/trackers/ParameterRegionTracker.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/trackers/generatedcode/LombokTracker.java
`MethodDeclarationTree` contains all the records deserialized from `AnnotatorScanner` which stores declaration information for each method. This PR renames `MethodDeclarationTree` to `MethodRegistry` and `MethodNode` to `MethodRecord` to better reflect the class purpose.
=> Rename MethodDeclarationTree to MethodRegistry

annotator-core/src/main/java/edu/ucr/cs/riple/core/Config.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/index/Index.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/util/Utility.java, annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/Utility.java
This PR is a follow up for #178 to only mock `buildTarget` static method and call the actual method for other static methods. This will enable us to reuse the methods in the mocked `Utility` class without requiring writing a mock for each method.
=> Mock only buildTarget static method

injector/src/main/java/edu/ucr/cs/riple/injector/changes/AddMarkerAnnotation.java, injector/src/main/java/edu/ucr/cs/riple/injector/changes/AddSingleElementAnnotation.java, injector/src/main/java/edu/ucr/cs/riple/injector/changes/RemoveMarkerAnnotation.java
This PR adds the missing `equals` and `hashcode` definitions in #186.
=> Add missing equals and hashcode to Change subclasses

annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/Registry.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/field/FieldInitializationStore.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/field/FieldRegistry.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/index/NonnullStore.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/method/MethodRegistry.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/trackers/FieldRegionTracker.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/trackers/MethodRegionTracker.java
This PR renames `MetaData` to `Registry` along refactoring its implementation. It updates its primary storage to `ImmutableMultiMap` from `MultiMap`.
Previous to this PR, `MetaData` was holding collection of `Nodes`. With new naming scheme, `Registry` is storing collection of `Records`.
=> Refactor MetaData class

annotator-scanner/src/test/java/edu/ucr/cs/riple/scanner/ClassRecordTest.java, annotator-scanner/src/test/java/edu/ucr/cs/riple/scanner/ConfigurationTest.java, annotator-scanner/src/test/java/edu/ucr/cs/riple/scanner/MethodRecordTest.java, annotator-scanner/src/test/java/edu/ucr/cs/riple/scanner/tools/ClassRecordDisplay.java, annotator-scanner/src/test/java/edu/ucr/cs/riple/scanner/tools/MethodRecordDisplay.java
Followup to PR #195, this PR renames remaining classes in `test` directory. It renames `MethodInfoDisplay` to `MethodRecordDisplay` and `ClassInfoDisplay` to `ClassRecordDisplay`.
=> Rename display subclasses in scanner/test

annotator-core/src/test/java/edu/ucr/cs/riple/core/CoreTest.java, annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/CoreTestHelper.java
Simple rename of `checkoutExpectedOutput` to `checkExpectedOutput`.
=> Rename checkExpectedOutput method name

annotator-core/build.gradle, annotator-scanner/build.gradle, gradle.properties
This PR removes `signAllPublications` for publish scripts and adds `RELEASE_SIGNING_ENABLED` flag to `gradle.properties`. This will allow us to control signing requirement using `ORG_GRADLE_PROJECT_RELEASE_SIGNING_ENABLED` flag while making local releases.
=> Disable signing for all publishes

annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/suppliers/DownstreamDependencySupplier.java, annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/CoreTestHelper.java, annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/ProjectBuilder.java
This PR updates tests infrastructure to compute distinct commands for building target and downstream dependencies. This will reveal a bug in the implementation which is also fixed in this PR.
=> Update tests to compute distinct build command for target and downstream depenedencies

annotator-core/src/main/java/edu/ucr/cs/riple/core/util/Utility.java
Resolves #205. This PR refactors std error output collection by using `Redirect.INHERIT` API. It also adds collecting std out of the child process (module builds) and prints them along the std error if `-rboserr` is set.
=> Collect std out using Redirect.INHERIT API

annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/downstream/DownstreamImpact.java
This PR removes redundant computation of `effect` in `DownstreamImpact` as it has no usage anywhere in the code. It is prerequisite for the upcoming PR resolving #209.
=> Remove redundant effect computation

annotator-core/src/test/java/edu/ucr/cs/riple/core/CoreTest.java, annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/CoreTestHelper.java, annotator-core/src/test/resources/templates/nullable-multi-modular/build.gradle, annotator-scanner/src/main/java/edu/ucr/cs/riple/scanner/location/MethodParameterLocation.java
This PR fixes #212 by updating method signature serialization for nonnull formal parameters. It reuses the existing serialization methods for symbols that ensure the correct method signature is printed.
=> Updates method signature serialization for Nonull formal parameters

annotator-scanner/src/main/java/edu/ucr/cs/riple/scanner/location/FieldLocation.java, annotator-scanner/src/main/java/edu/ucr/cs/riple/scanner/location/MethodLocation.java, annotator-scanner/src/main/java/edu/ucr/cs/riple/scanner/location/MethodParameterLocation.java
Followup to #213, this PR fixes symbol serialization in all `Location` subclasses.
=> Updates symbol serialization in all Location subclasses in Scanner

OPTIONS.md, README.md
@nimakarimipour  I moved the optional args to OPTIONS.md, only keeping the ones that are most useful to the user on the Readme. Let me know if more changes are needed.
=> chore(readme): moves optional agrs to own file for readability

annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/downstream/DownstreamImpactCacheImpl.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/method/MethodRecord.java
Minor refactoring on downstream dependencies cache implementation, preparing code for the upcoming changes.
=> Refactoring downstream dependency cache

annotator-core/build.gradle
We no longer have tests incompatible with older versions of NullAway. All our tests are compatible with latest supporting version of NullAway (0.10.19). This PR clean ups our test configuration.
=> Clean up in annotator core test configuration

annotator-core/src/test/java/edu/ucr/cs/riple/core/Java17Test.java, injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java
Fixes #225 . This is a follow up on #223 which adds support for processing source code written in java `17`. However, it was observed that support for modifications to `record` declarations were left out. This pull request addresses this issue.
=> Add support for fixes on record declarations

annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/field/FieldRegistry.java, annotator-core/src/test/java/edu/ucr/cs/riple/core/CoreTest.java
In [FieldRegistryPopulation](https://github.com/ucr-riple/NullAwayAnnotator/blob/6c17b8bccb08517f5ce3249d3285405ceeb47748/annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/field/FieldRegistry.java#L97) we process a single compilation unit tree multiple times as this method receives a pair of a class flat name and a path to source file containing that class, hence, for compilation unit trees that contains multiple classes, inner classes and anonymous classes we parse the same source file multiple times. This PR updates this mechanism by caching the latest parsed source file. This optimization is according to the assumption that Scanner visits all classes within a single compilation unit tree consecutively.
=> Optimize field registry population mechanism by parsing each source file only once

annotator-core/src/main/java/edu/ucr/cs/riple/core/Config.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/downstream/DownstreamImpactCacheImpl.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/injectors/PhysicalInjector.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/module/ModuleInfo.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/Registry.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/field/FieldInitializationStore.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/field/FieldRegistry.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/index/NonnullStore.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/method/MethodRegistry.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/region/CompoundRegionRegistry.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/region/FieldRegionRegistry.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/region/MethodRegionRegistry.java, annotator-core/src/test/java/edu/ucr/cs/riple/core/Java17Test.java, annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/CoreTestHelper.java, gradle.properties, injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java, injector/src/main/java/edu/ucr/cs/riple/injector/Injector.java
Needed to work around https://github.com/javaparser/javaparser/issues/4041.  Users impacted by that issue can set the language level to 11, assuming they are not using language constructs introduced after that version.
=> Add a language level option for parsing

gradle/dependencies.gradle
Upgrades javaparser to version `3.26.0`. Fixes the issue with `sealed`/`permits` used as variables.
=> Upgrade javaparser to 3.26.0

annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/field/ClassFieldRecord.java
This PR improves the memory usage of `FieldDeclarationNode` instances, significantly reducing the memory allocation during the execution of Annotator. The main change involves replacing the reference to `DeclarationNode` with boolean variables, which store the necessary information previously retrieved through the `DeclarationNode` reference.
=> Optimize memory usage for FieldDeclarationNode

annotator-core/src/main/java/edu/ucr/cs/riple/core/module/ModuleConfiguration.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/module/ModuleInfo.java
This PR introduces a check on the `AnnotatorScanner` output and notifies the user if `AnnotatorScanner` is incorrectly configured or has crashed. Before this PR, the Annotator would simply crash with a 'nonnull_elements.tsv not found' error (generated by AnnotatorScanner), which did not clearly indicate the underlying issue.
This PR is also related to #238.
=> Add check for scanner output

.github/workflows/continuous-integration.yml
This PR resolves [issue](https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/) that causes to CI for task `build-with-upload`.
=> Fix CI deprecation error v2 to v4

.github/workflows/continuous-integration.yml
This PR resolves [issue](https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/) and upgrades all actions versions from `v2` to `v4`.
=> Upgrade action versions from v2 to v4

annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/downstream/DownstreamImpactCacheImpl.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/checkers/nullaway/NullAway.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/graph/Node.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/graph/processors/AbstractConflictGraphProcessor.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/index/Error.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/index/Fix.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/region/generatedcode/LombokHandler.java, annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/TFix.java, annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/TReport.java
This PR removes the unused flag `fixIsSource` which indicates if the fix is suggested from an error in the source code of target or downstream dependency. This flag is not used in the latest logic anymore and is redundant. This PR removes this flag from the fix class declaration.
=> clean up fixIsSource flag from fix class

annotator-core/src/main/java/edu/ucr/cs/riple/core/checkers/Checker.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/checkers/nullaway/NullAway.java
This PR is a cleanup that is required before the upcoming major PR that adds support for taint checker inference.
Method `checker#createErrorToSubclass` is only used in subclass instance. This PR moves the declaration to the subclass that uses this method and removes it from the super class.
=> Move createErrorToSubclass method to subclass

annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/downstream/DownstreamImpactCacheImpl.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/checkers/nullaway/NullAway.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/graph/processors/AbstractConflictGraphProcessor.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/index/Error.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/index/Fix.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/region/generatedcode/LombokHandler.java, annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/TFix.java, annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/TReport.java
This PR is a cleanup that is required before the upcoming major PR that adds support for taint checker inference.
Changes:
Removed the reason property from the Fix class. Previously, this field stored the set of errors associated with each fix. However, this information can be derived directly from the set of errors itself.
Refactored the code to remove redundant storage, ensuring a cleaner and more efficient design.
Rationale:
The reason property is redundant as the same information is accessible through the error set. This refactoring simplifies the codebase and eliminates unnecessary complexity, making future updates, including the taint checker inference integration, easier to manage.
=> Clean up Fix class and remove reason property from class decl

injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java
This PR resolves a bug in Injector utility methods. The type for field declaration were not computed correctly  and the raw type was returned with can loose some important information. This PR fixes that.
=> Bug fix in Injector Helper API for field declaration type computation

annotator-core/src/main/java/edu/ucr/cs/riple/core/checkers/nullaway/NullAway.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/field/FieldRegistry.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/method/MethodRegistry.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/region/Region.java, annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/CoreTestHelper.java, injector/src/main/java/edu/ucr/cs/riple/injector/Injector.java, injector/src/main/java/edu/ucr/cs/riple/injector/Printer.java, injector/src/main/java/edu/ucr/cs/riple/injector/SignatureMatcher.java, injector/src/main/java/edu/ucr/cs/riple/injector/changes/AddTypeUseMarkerAnnotation.java, injector/src/main/java/edu/ucr/cs/riple/injector/changes/ChangeVisitor.java, injector/src/main/java/edu/ucr/cs/riple/injector/changes/Name.java, injector/src/main/java/edu/ucr/cs/riple/injector/changes/RemoveTypeUseMarkerAnnotation.java, injector/src/main/java/edu/ucr/cs/riple/injector/changes/TypeUseAnnotationChange.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/Location.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/OnClass.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/OnClassDeclaration.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/OnField.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/OnLocalVariable.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/OnMethod.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/OnParameter.java, injector/src/main/java/edu/ucr/cs/riple/injector/util/ASTUtils.java, injector/src/main/java/edu/ucr/cs/riple/injector/util/TypeUtils.java, injector/src/test/java/edu/ucr/cs/riple/injector/ClassSearchTest.java
This PR splits all utility methods in `Helper` class into two different classes. (`TypeUtils` and `ASTUtils`). This can wait for #251.
This PR only moves methods among classes, there is not a single change on any method declaration or implementation.
=> Split utility methods into two separate util class

injector/src/main/java/edu/ucr/cs/riple/injector/changes/TypeArgumentChangeVisitor.java, injector/src/test/java/edu/ucr/cs/riple/injector/TypeUseAnnotationTest.java
This PR fixes a bug in handling type arguments where arrays with primitive component types were incorrectly processed. The issue stemmed from an assumption that type arguments could not be primitives. However, we missed the case where an array used as a type argument can have a primitive component type.
To resolve this, the relevant method in TypeArgChangeVisitor is now overridden to account for arrays with primitive component types used as type arguments. This ensures that the appropriate changes are applied consistently.
=> Resolve Issue with Arrays of Primitive Component Types as Type Arguments

injector/src/test/java/edu/ucr/cs/riple/injector/TypeUseAnnotationTest.java
This PR adds test cases for the addition and deletion of annotations on the component type of arrays. It includes tests to verify successful annotation updates for arrays containing both primitive types and wrapper class types.
=> Add test cases for annotation insertion/deletion on array component type.

injector/src/main/java/edu/ucr/cs/riple/injector/changes/AddMarkerAnnotation.java, injector/src/test/java/edu/ucr/cs/riple/injector/BasicTest.java
This PR resolves #262 where Annotator adds duplicate `@Nullable` annotations to fields that already have a `@Nullable` annotation with comments.
The issue occurred because the equality check for annotations was based on the entire annotation node, which includes comments, rather than just the annotation's name. This PR updates the equality check logic to compare annotations based solely on their names, ensuring that existing annotations are correctly detected and duplicates are avoided.
=> Fix Duplicate @Nullable Annotations by fixing Equality Check

annotator-core/build.gradle, annotator-core/src/main/java/edu/ucr/cs/riple/core/Config.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/module/ModuleConfiguration.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/index/Fix.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/util/JsonParser.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/util/Utility.java, gradle/dependencies.gradle, injector/build.gradle, injector/src/main/java/edu/ucr/cs/riple/injector/location/Location.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/LocationToJsonVisitor.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/OnClassDeclaration.java
This PR updates the project's JSON handling dependency from `json-simple` to `GSON`. The switch to `GSON` addresses the need to suppress unchecked warnings (`@SuppressWarnings("unchecked")`) that were frequently required with `json-simple`. This change is also a proactive step in preparation for upcoming updates involving automatic source code fixes, which will heavily rely on JSON deserialization and parsing APIs, particularly for handling network connections and response parsing.
=> Change json dependency from json-simple to GSON

annotator-core/src/main/java/edu/ucr/cs/riple/core/checkers/nullaway/NullAway.java, annotator-core/src/main/java/edu/ucr/cs/riple/core/util/Utility.java
This PR updates the Nullaway Annotator to treat nullable annotations from the `checkers `and `jspecify` frameworks as type-use annotations. This change helps to align with the expected behavior of these frameworks.
=> Use TypeUse Annotations for Jspecify and Checkers frameworks

injector/src/main/java/edu/ucr/cs/riple/injector/changes/RemoveTypeUseMarkerAnnotation.java, injector/src/main/java/edu/ucr/cs/riple/injector/changes/TypeArgumentChangeVisitor.java, injector/src/test/java/edu/ucr/cs/riple/injector/TypeUseAnnotationTest.java
With the new specification for @Nullable type-use annotations, the correct placement for annotating the component type of an array is as follows:
```java
@Nullable Object arr[]
```
However, when parsing this expression, Javaparser associates the annotation with the entire `Object[] arr` node rather than the intended component type `@Nullable Object`.
This PR addresses this issue by adding a workaround ensuring correct annotation placement and includes a comprehensive set of tests to validate the fix.
=> Fix issue with adding/removing type use annotations on array component type.

annotator-core/src/main/java/edu/ucr/cs/riple/core/checkers/nullaway/NullAway.java, annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/Utility.java
This PR updates two occurrences where hardcoded serialization version values were used for NullAway support. Instead of using fixed values, the code now references the corresponding variable (`NullAway.VERSION`), improving maintainability.
=> Remove NullAway supported serialization version hardcoded values.

annotator-core/build.gradle, annotator-core/src/test/java/edu/ucr/cs/riple/core/CoreTest.java, annotator-core/src/test/resources/assignNullableToNonnullArrayComponentTypeLocalVariableTest/expected/Target/src/main/java/test/Main.java, injector/src/main/java/edu/ucr/cs/riple/injector/location/Location.java
This PR enables the annotator to deserialize errors from Nullaway that have Local Variable LocationKind. This helps to correctly annotate arrays that are declared as local variables.
=> Support local variable arrays
